# Generated by Django 3.2.15 on 2022-08-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220811_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='TravelLocation',
        ),
    ]
