# Generated by Django 3.2.15 on 2022-08-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_location_travellocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
    ]
