# Generated by Django 3.2.15 on 2022-08-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='travellocation',
            name='map_x',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travellocation',
            name='map_y',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
    ]
