# Generated by Django 3.2.15 on 2022-08-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220823_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.comment'),
            preserve_default=False,
        ),
    ]
