# Generated by Django 3.2.15 on 2022-09-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220907_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_level',
            field=models.IntegerField(default=0),
        ),
    ]
