# Generated by Django 3.2.15 on 2022-09-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_comment_comment_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated', '-created', '-comment_group']},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.IntegerField(default=-1),
        ),
    ]
